apiVersion: v1
kind: Service
metadata:
  name: python-k8s-app
  labels:
    app: python-k8s-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: python-k8s-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

