image:
  repository: devpraveens/python-k8s-app
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: ""
  host: python.local
  path: /
  pathType: Prefix

resources: {}

podLabels:
  app: python-k8s-app

